from __future__ import annotations

from .empirical import EmpiricalSource


def uci_sources() -> tuple[EmpiricalSource, ...]:
    cc = "CC BY 4.0"
    return (
        EmpiricalSource(
            "Iris measurements",
            "biology",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",
            "10.24432/C56C76",
            "iris",
            ("sepal_length", "sepal_width", "petal_length", "petal_width"),
            "species",
            cc,
        ),
        EmpiricalSource(
            "Wine chemistry",
            "chemistry",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",
            "10.24432/C5PC7J",
            "wine",
            tuple(f"chemical_{i}" for i in range(1, 14)),
            "cultivar",
            cc,
        ),
        EmpiricalSource(
            "Auto MPG",
            "transport",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data",
            "10.24432/C5859H",
            "auto-mpg",
            (
                "cylinders",
                "displacement",
                "horsepower",
                "weight",
                "acceleration",
                "model_year",
                "origin",
            ),
            "mpg",
            cc,
        ),
        EmpiricalSource(
            "NASA airfoil self-noise",
            "aerodynamics",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/00291/airfoil_self_noise.dat",
            "10.24432/C5VW2C",
            "airfoil",
            (
                "frequency",
                "attack_angle",
                "chord_length",
                "free_stream_velocity",
                "displacement_thickness",
            ),
            "sound_pressure_db",
            cc,
        ),
        EmpiricalSource(
            "Abalone physical measurements",
            "biology",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data",
            "10.24432/C55C7W",
            "abalone",
            (
                "sex",
                "length",
                "diameter",
                "height",
                "whole_weight",
                "shucked_weight",
                "viscera_weight",
                "shell_weight",
            ),
            "rings",
            cc,
        ),
        EmpiricalSource(
            "Ionosphere radar",
            "radar",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data",
            "10.24432/C5W01B",
            "ionosphere",
            tuple(f"radar_{i}" for i in range(1, 35)),
            "return_class",
            cc,
        ),
        EmpiricalSource(
            "Sonar returns",
            "sonar",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/connectionist-bench/sonar/sonar.all-data",
            "10.24432/C5T01Q",
            "sonar",
            tuple(f"band_{i}" for i in range(1, 61)),
            "object_class",
            cc,
        ),
        EmpiricalSource(
            "Yacht hydrodynamics",
            "hydrodynamics",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/00243/yacht_hydrodynamics.data",
            "10.24432/C5XG7R",
            "yacht",
            (
                "center_buoyancy",
                "prismatic_coefficient",
                "length_displacement_ratio",
                "beam_draught_ratio",
                "length_beam_ratio",
                "froude_number",
            ),
            "residuary_resistance",
            cc,
        ),
    )
