from __future__ import annotations

from .empirical import EmpiricalSource


def uci_sources() -> tuple[EmpiricalSource, ...]:
    cc = "CC BY 4.0"
    return (
        EmpiricalSource(
            "Iris measurements",
            "biology",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",
            "10.24432/C56C76",
            "iris",
            ("sepal_length", "sepal_width", "petal_length", "petal_width"),
            "species",
            cc,
            "6f608b71a7317216319b4d27b4d9bc84e6abd734eda7872b71a458569e2656c0",
        ),
        EmpiricalSource(
            "Wine chemistry",
            "chemistry",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",
            "10.24432/C5PC7J",
            "wine",
            tuple(f"chemical_{i}" for i in range(1, 14)),
            "cultivar",
            cc,
            "6be6b1203f3d51df0b553a70e57b8a723cd405683958204f96d23d7cd6aea659",
        ),
        EmpiricalSource(
            "Auto MPG",
            "transport",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data",
            "10.24432/C5859H",
            "auto-mpg",
            (
                "cylinders",
                "displacement",
                "horsepower",
                "weight",
                "acceleration",
                "model_year",
                "origin",
            ),
            "mpg",
            cc,
            "48b830e11feee5572525f8f1691ddb9d38d3d7b7063edcd8fca672c2a5e17d8d",
        ),
        EmpiricalSource(
            "NASA airfoil self-noise",
            "aerodynamics",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/00291/airfoil_self_noise.dat",
            "10.24432/C5VW2C",
            "airfoil",
            (
                "frequency",
                "attack_angle",
                "chord_length",
                "free_stream_velocity",
                "displacement_thickness",
            ),
            "sound_pressure_db",
            cc,
            "74c75fd71783f1e6b71f8a622b993dc592897a97cd689c5090a07147a1b097b3",
        ),
        EmpiricalSource(
            "Abalone physical measurements",
            "biology",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data",
            "10.24432/C55C7W",
            "abalone",
            (
                "sex",
                "length",
                "diameter",
                "height",
                "whole_weight",
                "shucked_weight",
                "viscera_weight",
                "shell_weight",
            ),
            "rings",
            cc,
            "de37cdcdcaaa50c309d514f248f7c2302a5f1f88c168905eba23fe2fbc78449f",
        ),
        EmpiricalSource(
            "Ionosphere radar",
            "radar",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data",
            "10.24432/C5W01B",
            "ionosphere",
            tuple(f"radar_{i}" for i in range(1, 35)),
            "return_class",
            cc,
            "46d52186b84e20be52918adb93e8fb9926b34795ff7504c24350ae0616a04bbd",
        ),
        EmpiricalSource(
            "Sonar returns",
            "sonar",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/connectionist-bench/sonar/sonar.all-data",
            "10.24432/C5T01Q",
            "sonar",
            tuple(f"band_{i}" for i in range(1, 61)),
            "object_class",
            cc,
            "e90434cdbf00fcf93ffa911fe447ae25606979658e60f1d32e155c3b5240234d",
        ),
        EmpiricalSource(
            "Yacht hydrodynamics",
            "hydrodynamics",
            "https://archive.ics.uci.edu/ml/machine-learning-databases/00243/yacht_hydrodynamics.data",
            "10.24432/C5XG7R",
            "yacht",
            (
                "center_buoyancy",
                "prismatic_coefficient",
                "length_displacement_ratio",
                "beam_draught_ratio",
                "length_beam_ratio",
                "froude_number",
            ),
            "residuary_resistance",
            cc,
            "00dfecc0fc01ddd4c90b558a3ac11b246df8ebcfea130724223475a9a67f0ea1",
        ),
    )
